version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: resume_postgres
    environment:
      POSTGRES_DB: resume_db
      POSTGRES_USER: resume_user
      POSTGRES_PASSWORD: resume_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d/
    ports:
      - "5434:5432"
    networks:
      - resume_network
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: resume_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - resume_network
    restart: unless-stopped

  # Backend Gateway
  # backend-gateway:
  #   build:
  #     context: ./backend/gateway
  #     dockerfile: Dockerfile
  #   container_name: resume_backend_gateway
  #   environment:
  #     - DATABASE_URL=postgresql://resume_user:resume_password@postgres:5432/resume_db
  #     - QDRANT_URL=http://qdrant:6333
  #     - PORT=3001
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     - postgres
  #     - qdrant
  #     # - qdrant_migrations
  #   networks:
  #     - resume_network
  #   volumes:
  #     - ./datasets:/app/datasets
  #   restart: unless-stopped

  qdrant_migrations:
    build:
      context: ./qdrant_migrations
      dockerfile: Dockerfile
    container_name: resume_qdrant_migrations
    environment:
      - POSTGRES_DB=resume_db
      - POSTGRES_USER=resume_user
      - POSTGRES_PASSWORD=resume_password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - postgres
      - qdrant
    networks:
      - resume_network
    restart: no

  ml-llm:
    build:
      context: ./ml/llm
      dockerfile: Dockerfile
    container_name: resume_ml_llm
    environment:
      - PORT=8000
      - QDRANT_URL=http://qdrant:6333
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    networks:
      - resume_network
    volumes:
      - huggingface_cache:/root/.cache/huggingface
    restart: unless-stopped

  # ml-embedder:
  #   build:
  #     context: ./ml/embedder
  #     dockerfile: Dockerfile
  #   container_name: resume_ml_embedder
  #   environment:
  #     - PORT=8001
  #     - QDRANT_URL=http://qdrant:6333
  #   ports:
  #     - "8001:8001"
  #   depends_on:
  #     - qdrant_migrations
  #   networks:
  #     - resume_network
  #   volumes:
  #     - huggingface_cache:/root/.cache/huggingface
  #     - sentence_transformers_cache:/root/.cache/torch/sentence_transformers
  #   restart: unless-stopped

  # Frontend
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: resume_frontend
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:3001
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend-gateway
  #   networks:
  #     - resume_network
  #   restart: unless-stopped

volumes:
  postgres_data:
  qdrant_data:
  huggingface_cache:
  sentence_transformers_cache:

networks:
  resume_network:
    driver: bridge